## Contents
- Creating a Dataframe
- Selection and indexing of columns
- Creating a new column 
- Removing columns 
- Selecting rows 
- Selecting subsets of Rows and columns 
- conditional selection

In [2]:
import numpy as np
import pandas as pd

Creating a Dataframe

In [3]:
data = {
    "Name": ["John", "Anna", "Peter", "Linda"],
    "Age": [28, 34, 29, 42],
    "City": ["New York", "Paris", "Berlin", "London"],
    "Salary": [65000, 70000, 62000, 85000],
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ["John", 28, "New York", 65000],
    ["Anna", 34, "Paris", 70000],
    ["Peter", 29, "Berlin", 62000],
    ["Linda", 42, "London", 85000],
]

df2 = pd.DataFrame(data_list)

In [6]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [7]:
columns = ["Name", "Age", "City", "Salary"]
df3 = pd.DataFrame(data_list, columns=columns)

In [8]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns

In [9]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df3['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [11]:
df3['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [12]:
df3[["Name", "City", "Age"]]

    Name      City  Age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

Creating a new column

In [13]:
df3

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [14]:
df3['Address'] = ["Meerut", "Bhagalpur", "Surat", "Delhi"]

In [15]:
df3

    Name  Age      City  Salary    Address
0   John   28  New York   65000     Meerut
1   Anna   34     Paris   70000  Bhagalpur
2  Peter   29    Berlin   62000      Surat
3  Linda   42    London   85000      Delhi

In [16]:
df3[["Designation", "Experience"]] = pd.DataFrame({
    "Designation": ["Doctor", "Engineer", "Scientist", "IAS"],
    "Experience": [2, 3, 4, 5],
})

In [17]:
df3

    Name  Age      City  Salary    Address Designation  Experience
0   John   28  New York   65000     Meerut      Doctor           2
1   Anna   34     Paris   70000  Bhagalpur    Engineer           3
2  Peter   29    Berlin   62000      Surat   Scientist           4
3  Linda   42    London   85000      Delhi         IAS           5

In [18]:
col = df3.drop("Age", axis=1)
col

    Name      City  Salary    Address Designation  Experience
0   John  New York   65000     Meerut      Doctor           2
1   Anna     Paris   70000  Bhagalpur    Engineer           3
2  Peter    Berlin   62000      Surat   Scientist           4
3  Linda    London   85000      Delhi         IAS           5

In [19]:
df3.drop("Name", axis=1)

   Age      City  Salary    Address Designation  Experience
0   28  New York   65000     Meerut      Doctor           2
1   34     Paris   70000  Bhagalpur    Engineer           3
2   29    Berlin   62000      Surat   Scientist           4
3   42    London   85000      Delhi         IAS           5

In [20]:
df3

    Name  Age      City  Salary    Address Designation  Experience
0   John   28  New York   65000     Meerut      Doctor           2
1   Anna   34     Paris   70000  Bhagalpur    Engineer           3
2  Peter   29    Berlin   62000      Surat   Scientist           4
3  Linda   42    London   85000      Delhi         IAS           5

In [21]:
df3 = df3.drop("City", axis=1)

In [22]:
df3

    Name  Age  Salary    Address Designation  Experience
0   John   28   65000     Meerut      Doctor           2
1   Anna   34   70000  Bhagalpur    Engineer           3
2  Peter   29   62000      Surat   Scientist           4
3  Linda   42   85000      Delhi         IAS           5

In [23]:
df3.drop("Address", axis=1, inplace=True)

In [24]:
df3

    Name  Age  Salary Designation  Experience
0   John   28   65000      Doctor           2
1   Anna   34   70000    Engineer           3
2  Peter   29   62000   Scientist           4
3  Linda   42   85000         IAS           5

In [25]:
df3

    Name  Age  Salary Designation  Experience
0   John   28   65000      Doctor           2
1   Anna   34   70000    Engineer           3
2  Peter   29   62000   Scientist           4
3  Linda   42   85000         IAS           5

In [26]:
df3.drop(["Designation", "Experience"], axis=1, inplace=True)

In [27]:
df3

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [28]:
# remove row
df.drop(0, axis=0, inplace=True)
df

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [29]:
df.drop([2,3], inplace=True)

In [30]:
df

   Name  Age   City  Salary
1  Anna   34  Paris   70000

Selecting rows

In [31]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [32]:
df2 = pd.DataFrame(data_list, columns=columns)

In [33]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [35]:
df2.loc[[1,2]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000

In [36]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [37]:
df

   Name  Age   City  Salary
1  Anna   34  Paris   70000

Selecting subsets of rows and columns

In [40]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [43]:
df2.loc[[0,1]][["City", "Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [46]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  Peter   29
3  Linda   42

Conditional Selection

In [47]:
# I only want to see those people whose age is above 30

df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [51]:
# i only want people whose age is above 30 and their city must be paris

df2[((df2['Age'] > 30) & (df2['City'] == 'Paris'))]

   Name  Age   City  Salary
1  Anna   34  Paris   70000